# Generated by Django 5.1.3 on 2024-11-24 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='matched_users',
        ),
        migrations.AddField(
            model_name='matching',
            name='matched_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matched_with', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matching',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
