# Generated by Django 5.1.3 on 2024-11-24 22:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_matching', '0002_remove_matching_matched_users_matching_matched_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together={('user', 'matched_user')},
        ),
    ]
