# Generated by Django 5.1.3 on 2024-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_matching', '0004_alter_matching_unique_together_alter_matching_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
