# Generated by Django 5.1.3 on 2024-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preference', '0002_remove_userpreference_income_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
