# Generated by Django 5.1.3 on 2024-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preference', '0003_alter_userpreference_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='id',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preference_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
