# Generated by Django 5.1.3 on 2024-11-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preference', '0005_userpreference_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
