# Generated by Django 5.1.3 on 2024-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preference', '0006_userpreference_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
