# Generated by Django 5.1.3 on 2024-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preference', '0007_userpreference_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
