# Generated by Django 5.1.3 on 2024-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryvalue',
            name='id',
        ),
        migrations.AddField(
            model_name='categoryvalue',
            name='value_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
