# Generated by Django 5.1.3 on 2024-11-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_rename_category_id_categoryvalue_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryvalue',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AlterUniqueTogether(
            name='categoryvalue',
            unique_together={('category_id', 'category_value')},
        ),
    ]
