# Generated by Django 5.1.3 on 2024-11-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_rename_category_categoryvalue_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(blank=True, max_length=150, null=True)),
                ('subscription_duration', models.PositiveIntegerField(blank=True)),
                ('subscription_description', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
