# Generated by Django 5.1.3 on 2024-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_subscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
