# Generated by Django 5.1.3 on 2024-11-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_alter_subscription_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
