# Generated by Django 5.1.3 on 2024-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_remove_userprofile_id_userprofile_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
