# Generated by Django 5.1.3 on 2024-11-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0007_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='income',
        ),
    ]
