# Generated by Django 5.1.3 on 2024-11-16 08:44

import app_user_authentications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetupmodel',
            name='phone_no',
            field=models.CharField(default=1, help_text='Enter a valid phone number', max_length=10, validators=[app_user_authentications.validators.validate_phone_number]),
            preserve_default=False,
        ),
    ]
