# Generated by Django 5.1.3 on 2024-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0002_alter_usersetupmodel_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetupmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
