# Generated by Django 5.1.3 on 2024-11-18 10:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0003_alter_usersetupmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersetupmodel',
            managers=[
                ('admin_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
