# Generated by Django 5.1.3 on 2024-11-19 11:55

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0004_alter_usersetupmodel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersetupmodel',
            managers=[
                ('active_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
