# Generated by Django 5.1.3 on 2024-11-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0006_refreshtokenstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshTokenStore',
        ),
    ]
