# Generated by Django 5.1.3 on 2024-11-19 19:06

import app_user_authentications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0007_delete_refreshtokenstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetupmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usersetupmodel',
            name='phone_no',
            field=models.CharField(help_text='Enter a valid phone number', max_length=10, unique=True, validators=[app_user_authentications.validators.validate_phone_number]),
        ),
    ]
