# Generated by Django 5.1.3 on 2024-11-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_userprofile_phone_number'),
        ('app_user_authentications', '0008_alter_usersetupmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetupmodel',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_profile.userprofile'),
        ),
    ]
