# Generated by Django 5.1.3 on 2024-11-25 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0010_alter_usersetupmodel_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetupmodel',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
