# Generated by Django 5.1.3 on 2024-11-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preference', '0009_alter_userpreference_user'),
        ('app_user_authentications', '0011_usersetupmodel_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetupmodel',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preference', to='app_preference.userpreference'),
        ),
    ]
