# Generated by Django 5.1.3 on 2024-11-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentications', '0012_usersetupmodel_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetupmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersetupmodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
