# Generated by Django 5.1.3 on 2024-11-28 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text="The user's access token")),
                ('refresh_token', models.TextField(help_text="The user's refresh token")),
                ('access_token_active', models.BooleanField(default=True, help_text='State of the access token: Active or Inactive')),
                ('refresh_token_active', models.BooleanField(default=True, help_text='State of the refresh token: Active or Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the tokens were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time when the tokens were last updated')),
                ('user', models.ForeignKey(help_text='The user associated with the tokens', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Storage',
                'verbose_name_plural': 'Token Storage',
            },
        ),
    ]
