# Generated by Django 5.1.3 on 2024-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstorage',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenstorage',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
