# Generated by Django 5.1.3 on 2024-11-25 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connection_handler', '0002_alter_friendrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='blocked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
